### ISSUE TITLE
How are you importing SessionStore?

### ISSUE THREAD

**Issue by RohanAntony** [mweibel/connect-session-sequelize#109]
```
var Session = sequelize.define("Session", {
  sid: {
    type: Sequelize.STRING,
    primaryKey: true,
  },
  userId: Sequelize.STRING,
  expires: Sequelize.DATE,
  data: Sequelize.STRING(50000),
});

function extendDefaultFields(defaults, session) {
  return {
    data: defaults.data,
    expires: defaults.expires,
    userId: session.userId,
  };
}

var store = new SessionStore({
  db: sequelize,
  table: "Session",
  extendDefaultFields: extendDefaultFields,
});
```

1. For all the previous examples, there is only use of SequelizeStore but for the last example, you seem to be using the class SessionStore. How are you importing it? Is it the same as the class SequelizeStore? If yes, please rename it or add an import.
2. What is the reason for defining "Session" object if its not passed as parameter, its being defined but not used in the code which seems confusing. Please call only sequelize.define() without the `var Session`

**Comment by RohanAntony** [comment]
PS: I tried using SequelizeStore and it worked. I think you should abstract the definition of Table to something like below.

```
new SequelizeStore({
  additionalFields: {
    userId: Sequelize.STRING,
  },
  extendDefaultFields: function(defaults, newData){
    defaults['userId']: newData.userId
  }
})
```

**Comment by mweibel** [comment]
Hey,

Feel free to send a PR with proposed changes. 

Cheers
Michael

**Comment by MarlonS91** [comment]
I am having the same problem as outlined by @RohanAntony.

**Comment by MarlonS91** [comment]
I also received an error ...

```javascript
// as specified by doc
// ref: https://github.com/mweibel/connect-session-sequelize#add-custom-fields-as-a-column

var Session = sequelize.define("Session", {
  sid: {
    type: Sequelize.STRING,
    primaryKey: true,
  },
  userId: Sequelize.STRING,
  expires: Sequelize.DATE,
  data: Sequelize.STRING(50000), // throws SequelizeDatabaseError
});

function extendDefaultFields(defaults, session) {
  return {
    data: defaults.data,
    expires: defaults.expires,
    userId: session.userId,
  };
}

var store = new SessionStore({
  db: sequelize,
  table: "Session",
  extendDefaultFields: extendDefaultFields,
});
```
```console
Unhandled rejection SequelizeDatabaseError: Column length too big for column 'data' (max = 21845); use BLOB or TEXT instead
    at Query.formatError (/home/sunami/Projects/plugged-backend/node_modules/sequelize/lib/dialects/mysql/query.js:244:16)
    at Query.handler [as onResult] (/home/sunami/Projects/plugged-backend/node_modules/sequelize/lib/dialects/mysql/query.js:51:23)
    at Query.execute (/home/sunami/Projects/plugged-backend/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/home/sunami/Projects/plugged-backend/node_modules/mysql2/lib/connection.js:417:32)
    at PacketParser.onPacket (/home/sunami/Projects/plugged-backend/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/home/sunami/Projects/plugged-backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/sunami/Projects/plugged-backend/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:304:12)
    at readableAddChunk (_stream_readable.js:280:9)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by mweibel** [comment]
I repeat myself: I welcome PRs for updating the docs.
