### ISSUE TITLE
Session not saving in database

### ISSUE THREAD

**Issue by peterd130** [mweibel/connect-session-sequelize#141]
I'm getting this error:

```
Executing (default): INSERT INTO `Sessions` (`sid`,`expires`,`data`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?);
Error
    at Query.run (/app/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)
    at /app/node_modules/sequelize/lib/sequelize.js:314:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MySQLQueryInterface.insert (/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:308:21)
    at async model.save (/app/node_modules/sequelize/lib/model.js:2432:35)
    at async Session.create (/app/node_modules/sequelize/lib/model.js:1344:12)
    at async Session.findCreateFind (/app/node_modules/sequelize/lib/model.js:1458:23)
```

My middleware:

```
app.use(session({
    secret: "thisismysecrctekey",
    store: new SessionStore({
      db: connection
    }),
    cookie: {
      httpOnly: true,
      secure: false
    },
    genid: function(req) {
      return uuid()
    },
    saveUninitialized: false,
    name : 'sessionId',
    resave: false
  })
)
```

**Comment by peterd130** [comment]
Apparently there was something wrong with the 'Sessions' table. I deleted and created again with store.sync() and everything went fine
