### ISSUE TITLE
Error at Query.run > Inserting session data into database

### ISSUE THREAD

**Issue by josegabrielc** [mweibel/connect-session-sequelize#146]
Hi,

My query and session return to the client is working normally however there is no record being created in the database.

Log from my console: 

`Executing (default): INSERT INTO `sessions` (`sid`) VALUES (?);
Error
    at Query.run (C:\Users\joseg\Desktop\horizon\api\node_modules\sequelize\lib\dialects\mysql\query.js:52:25)
    at C:\Users\joseg\Desktop\horizon\api\node_modules\sequelize\lib\sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MySQLQueryInterface.insert (C:\Users\joseg\Desktop\horizon\api\node_modules\sequelize\lib\dialects\abstract\query-interface.js:308:21)
    at async model.save (C:\Users\joseg\Desktop\horizon\api\node_modules\sequelize\lib\model.js:2490:35)
    at async sessions.create (C:\Users\joseg\Desktop\horizon\api\node_modules\sequelize\lib\model.js:1362:12)
    at async sessions.findCreateFind (C:\Users\joseg\Desktop\horizon\api\node_modules\sequelize\lib\model.js:1476:23)`

What could be happening?

**Comment by ragibayon** [comment]
I am facing the same issue

**Comment by ianchanning** [comment]
I've added a comment to this [StackOverflow question](https://stackoverflow.com/a/79514200/327074).

There should be a database error displayed after "Error" `Error <actual database error missing> at Query.run`.

I haven't found a way to display this error yet - but you can turn on Sequelize database logging and the see what is the last query that runs before the error shows and and then run that query manually on the database

**Comment by mweibel** [comment]
any update on this one? did you find the underlying SQL error using the way described by @ianchanning?
