### ISSUE TITLE
Session destroy not removing entry from DB.

### ISSUE THREAD

**Issue by deepak-manwal** [mweibel/connect-session-sequelize#21]
Session get destroy successfully but and not removing entry form DB. Its giving error:

	Unhandled rejection TypeError: undefined is not a function
	    at errorDestroying (/home/costrategix/Node/project/node_modules/connect-session-sequelize/lib/connect-session-sequelize.js:157:11)
	    at tryCatcher (/home/costrategix/Node/project/node_modules/sequelize/node_modules/bluebird/js/main/util.js:26:23)
	    at Promise._settlePromiseFromHandler (/home/costrategix/Node/project/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:503:31)
	    at Promise._settlePromiseAt (/home/costrategix/Node/project/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:577:18)
	    at Promise._settlePromises (/home/costrategix/Node/project/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:693:14)
	    at Async._drainQueue (/home/costrategix/Node/project/node_modules/sequelize/node_modules/bluebird/js/main/async.js:123:16)
	    at Async._drainQueues (/home/costrategix/Node/project/node_modules/sequelize/node_modules/bluebird/js/main/async.js:133:10)
	    at Async.drainQueues (/home/costrategix/Node/project/node_modules/sequelize/node_modules/bluebird/js/main/async.js:15:14)
	    at process._tickCallback (node.js:415:13)

**Comment by jakeorr** [comment]
Hi Deepak, what version are you running?

**Comment by deepak-manwal** [comment]
I am using connect-session-sequelize 2.2.1.

**Comment by jakeorr** [comment]
Thanks for posting, I made a PR to change the `destroy()` callback to an optional argument.

**Comment by deepak-manwal** [comment]
Thanks for PR. But why its not clearing `Session` table from DB. Always coming At catch section

     catch(function errorDestroying(error) {
	debug('Error destroying session: %s', error);
	fn(error);//here its giving error
    });

**Comment by jakeorr** [comment]
Oh, sorry I misread the issue. I will have a closer look at this when I have a minute.

**Comment by deepak-manwal** [comment]
Ya you catched it. I am also looking into it. If i'll find any solution i'll make a pull request. This is big issue i'll keep track on this.

**Comment by jakeorr** [comment]
`.destroy()` is not throwing an error me. Can you show me how you are using it?

Your comment in the PR where you say:
> But its not clearing session at the time of Log Out.
Makes me think that maybe you are expecting the session store to delete your session record on log out. If so, you may be interested in reading about the `unset` option: https://github.com/expressjs/session#unset

**Comment by mweibel** [comment]
Closing this for now, if the suggested solution doesn't work, please reopen.

**Comment by deepak-manwal** [comment]
This is how i am using destroy:

    req.session.destroy();

Is this not correct way?

**Comment by jakeorr** [comment]
The PR that @mweibel just merged makes the callback optional so it should fix the error you are seeing.
