### ISSUE TITLE
Warning: a promise was created in a  handler but was not returned from it

### ISSUE THREAD

**Issue by bpmckee** [mweibel/connect-session-sequelize#30]
The latest version of bluebird promise throws a warning when a promise does not have a return value.  Apparently one solution to stop this warning is to just return null in all promises that don't have a return statement in them.

I've seen this warning thrown from multiple places in this module.  Here's one I just grabbed from my logs.
```
Warning: a promise was created in a  handler but was not returned from it
    at [object Object].Model.update (<project path>/node_modules/sequelize/lib/model.js:2423:21)
    at SequelizeStore.touchSession [as touch] (<project path>/node_modules/connect-session-sequelize/lib/connect-session-sequelize.js:131:23)
```

**Comment by mweibel** [comment]
Which version of the module are you using? Also you're welcome to open a PR :+1:

**Comment by bpmckee** [comment]
Here are the relevant versions of things.
```
"bluebird": "^3.0.5",
"connect-session-sequelize": "^2.3.1",
"sequelize": "^3.15.0",
```

Also I might open one up in a couple days.  Pretty swamped until then.  Thanks! :)

**Comment by mweibel** [comment]
did you try the latest version of connect-session-sequelize? (3.0.0)

**Comment by Misiur** [comment]
I've just updated all deps and I stumbled upon this as well. 
Triggered by `response#json()` (sorry if irrevelant stacktrace).
```
Warning: a promise was created in a handler but was not returned from it
    at processImmediate [as _immediateCallback] (timers.js:368:17)
From previous event:
    at Model.update (d:\Dev\Dvlp\driver-server\node_modules\sequelize\lib\model.js:2437:21)
    at SequelizeStore.touchSession [as touch] (d:\Dev\Dvlp\driver-server\node_modules\connect-session-sequelize\lib\connect-session-sequelize.js:105:30)
    at ServerResponse.end (d:\Dev\Dvlp\driver-server\node_modules\express-session\index.js:301:15)
    at ServerResponse.send (d:\Dev\Dvlp\driver-server\node_modules\express\lib\response.js:204:10)
    at ServerResponse.json (d:\Dev\Dvlp\driver-server\node_modules\express\lib\response.js:249:15)
    at d:\Dev\Dvlp\driver-server\src\Web\Controllers\Auth.js:150:20
    at Layer.handle [as handle_request] (d:\Dev\Dvlp\driver-server\node_modules\express\lib\router\layer.js:95:5)
    at next (d:\Dev\Dvlp\driver-server\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (d:\Dev\Dvlp\driver-server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (d:\Dev\Dvlp\driver-server\node_modules\express\lib\router\layer.js:95:5)
    at d:\Dev\Dvlp\driver-server\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (d:\Dev\Dvlp\driver-server\node_modules\express\lib\router\index.js:330:12)
    at next (d:\Dev\Dvlp\driver-server\node_modules\express\lib\router\index.js:271:10)
    at Function.handle (d:\Dev\Dvlp\driver-server\node_modules\express\lib\router\index.js:176:3)
    at router (d:\Dev\Dvlp\driver-server\node_modules\express\lib\router\index.js:46:12)
From previous event:
    at Promise.then (d:\Dev\Dvlp\driver-server\node_modules\sequelize\lib\promise.js:21:17)
    at UserSchema.findByUsername (d:\Dev\Dvlp\driver-server\src\Web\passport-local-sequelize-roles.js:290:15)
    at d:\Dev\Dvlp\driver-server\src\Web\passport-local-sequelize-roles.js:177:25
    at pass (d:\Dev\Dvlp\driver-server\node_modules\passport\lib\authenticator.js:347:9)
    at Authenticator.deserializeUser (d:\Dev\Dvlp\driver-server\node_modules\passport\lib\authenticator.js:352:5)
    at SessionStrategy.authenticate (d:\Dev\Dvlp\driver-server\node_modules\passport\lib\strategies\session.js:53:28)
    at attempt (d:\Dev\Dvlp\driver-server\node_modules\passport\lib\middleware\authenticate.js:348:16)
    at authenticate (d:\Dev\Dvlp\driver-server\node_modules\passport\lib\middleware\authenticate.js:349:7)
    at Layer.handle [as handle_request] (d:\Dev\Dvlp\driver-server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\Dev\Dvlp\driver-server\node_modules\express\lib\router\index.js:312:13)
    at d:\Dev\Dvlp\driver-server\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\Dev\Dvlp\driver-server\node_modules\express\lib\router\index.js:330:12)
    at next (d:\Dev\Dvlp\driver-server\node_modules\express\lib\router\index.js:271:10)
    at initialize (d:\Dev\Dvlp\driver-server\node_modules\passport\lib\middleware\initialize.js:53:5)
    at Layer.handle [as handle_request] (d:\Dev\Dvlp\driver-server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\Dev\Dvlp\driver-server\node_modules\express\lib\router\index.js:312:13)
    at d:\Dev\Dvlp\driver-server\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (d:\Dev\Dvlp\driver-server\node_modules\express\lib\router\index.js:330:12)
    at next (d:\Dev\Dvlp\driver-server\node_modules\express\lib\router\index.js:271:10)
```

**Comment by crisward** [comment]
Any resolution to this yet? it's making my dev logs very unreadable.

**Comment by ilyakrupnov** [comment]
Same issue.

**Comment by mweibel** [comment]
As said: I welcome a PR to fix that, currently not that much time to test that. I'll also add anyone who contributes something significant as a contributor who can push code.

**Comment by mweibel** [comment]
I tried to reproduce this now but I can't. What's the setup needed? Also: PRs are more than welcome.

**Comment by urtubia** [comment]
Hey @mweibel I looked into it without much luck but I have a consistent repro scenario.
Clone: https://github.com/urtubia/react-redux-passport-sequelize-example (which is a fork of https://github.com/erikras/react-redux-universal-hot-example but using express-passport-sequelize for authentication)
Then 
* `nvm use 5`
* `npm install`
* `npm run dev`
* On another tab, do `npm run test-node`

Then you'll see the warnings popup.

**Comment by mweibel** [comment]
Awesome, thanks for the repro steps. Will check that out :+1:

**Comment by mweibel** [comment]
@urtubia this is a problem with your code. If I apply the following patch, it works:

```diff
diff --git a/api/utils/passportConfig.js b/api/utils/passportConfig.js
index 6078b32..35690bd 100644
--- a/api/utils/passportConfig.js
+++ b/api/utils/passportConfig.js
@@ -6,13 +6,16 @@ var LocalStrategy = passportLocal.Strategy;
 export default function configPassport(passport) {
   passport.serializeUser( (user, done) => {
     done(null, user.id);
+    return null;
   });

   passport.deserializeUser( (id, done) => {
     User.findOne({ where: {id: id} }).then( (user) => {
       done(null, user);
+      return null;
     }).catch((err) => {
       done(err, user);
+      return null;
     });
   });

@@ -30,9 +33,11 @@ export default function configPassport(passport) {
         }
       }).then(newUser => {
           done(null, newUser);
+          return null;
       }).catch(err => {
-        console.log(`Err ${err}`);
+        console.log(`Err ${err}`);
         done(err);
+        return null;
       });

     })}));
@@ -40,18 +45,22 @@ export default function configPassport(passport) {
   passport.use('local-login', new LocalStrategy({usernameField:'email', passwordField:'password', passReqToCallback: true}, (req, email, password, done) => {
     User.findOne({where: {email: email}}).then(user => {
       if(!user){
-        return done(null, false);
+        done(null, false);
+        return null;
       }

       if(!user.validPassword(password)){
-        return done(null, false);
+        done(null, false);
+        return null;
       }

       done(null, user);
+      return null;
     }).catch(err => {
       done(err);
+      return null;
     });

   }));
-
+
 }
```

See also: https://github.com/petkaantonov/bluebird/blob/master/docs/docs/warning-explanations.md#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it

**Comment by urtubia** [comment]
@mweibel great find, thanks for taking a look.

**Comment by lxcid** [comment]
I think I'm still facing this though.
