### ISSUE TITLE
call `unref`

### ISSUE THREAD

**Issue by tomfun** [mweibel/connect-session-sequelize#63]
I used your library for a long time. But in the last week after updating node js and some dependencies my tests stuck. After some investigation I found out that you don't call `unref`, your code:
```js
  SequelizeStore.prototype.startExpiringSessions = function startExpiringSessions () {
    // Don't allow multiple intervals to run at once.
    this.stopExpiringSessions()
    if (this.options.checkExpirationInterval > 0) {
      this._expirationInterval = setInterval(this.clearExpiredSessions.bind(this), this.options.checkExpirationInterval)
    }
  }
```
problem is solving by adding a line:
```js
  // ...
      this._expirationInterval = setInterval(this.clearExpiredSessions.bind(this), this.options.checkExpirationInterval)
      this._expirationInterval.unref() // < - -
  // ...
```
Please fix it.

p.s. I just can't understand why I strike with the problem just now, what I have changed, why it did work fine in the past?..

**Comment by mweibel** [comment]
Makes sense. Released Version 5.0.1 on NPM.

**Comment by manuelbieh** [comment]
Hmm looks like this causes problems elsewhere. I testing an express app using jest and I after adding ConnectSessionSequelize my tests fail with the following error:

```
 FAIL  route-controllers\users.test.js
  ● Test suite failed to run

    TypeError: this._expirationInterval.unref is not a function

      40 |
      41 | const SequelizeSessionStore = ConnectSessionSequelize(session.Store);
    > 42 | const sessionStoreInstance = new SequelizeSessionStore({
      43 |     db: sequelize,
      44 | });
      45 |

      at SequelizeStore.startExpiringSessions (node_modules/connect-session-sequelize/lib/connect-session-sequelize.js:163:32)
      at new SequelizeStore (node_modules/connect-session-sequelize/lib/connect-session-sequelize.js:41:10)
      at Object.<anonymous> (app.js:42:28)
      at Object.<anonymous> (route-controllers/users.test.js:1:370)
```

**Comment by tomfun** [comment]
It looks likr you run tests in non node js environment, but the library
can't work there, as sequelize

вс, 4 мар. 2018 г., 21:54 Manuel Bieh <notifications@github.com>:
