### ISSUE TITLE
sequelize sync

### ISSUE THREAD

**Issue by ryanburnette** [mweibel/connect-session-sequelize#77]
The sync snippet isn't working for me.

```
    throw new ERR_INVALID_ARG_TYPE('superCtor.prototype',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor.prototype" property must be of type Function. Received type undefined
    at Object.inherits (util.js:1350:11)
    at new SequelizeSessionInit (/Users/ryan/Development/app/node_modules/connect-session-sequelize/lib/connect-session-sequelize.js:55:8)
    at Object.<anonymous> (/Users/ryan/Development/app/support/sync.js:16:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
```

node 10.11.0
connect-session-sequelize 5.2.2
sequelize 4.40.0
sqlite3 4.0.2

**Comment by ryanburnette** [comment]
Related https://github.com/nodejs/node/issues/4179

**Comment by ryanburnette** [comment]
Node 8.12 gives me this error

```
    throw new TypeError('The super constructor to "inherits" must ' +
    ^

TypeError: The super constructor to "inherits" must have a prototype
    at Object.inherits (util.js:942:11)
    at new SequelizeSessionInit (/Users/ryan/Development/app/node_modules/connect-session-sequelize/lib/connect-session-sequelize.js:55:8)
    at Object.<anonymous> (/Users/ryan/Development/app/support/sync.js:16:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**Comment by mweibel** [comment]
What do you mean by sync snippet?

Other than that, I guess we'd need to update to ES6 syntax for classes (and also switch to const/let instead of var .. etc) and drop support for the old node versions which don't support this syntax. 
I'd welcome a PR with those changes.

**Comment by mweibel** [comment]
Closing due to inactivity.
